version: "3.9"

services:
  backend:
    build: "./VK Service Posting"
    container_name: backend
    env_file: "./VK Service Posting/.env"
    depends_on:
      - db
      - redis
    working_dir: /app
    volumes:
      - "./VK Service Posting:/app"
    ports:
      - "8000:8000"
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    environment:
      - PYTHONPATH=/app/src

  celery:
    build: "./VK Service Posting"
    container_name: celery
    env_file: "./VK Service Posting/.env"
    depends_on:
      - backend
      - redis
      - db
    volumes:
      - "./VK Service Posting:/app"
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    command: celery -A src.celery_app worker --loglevel=info --pool=solo

  frontend:
    build: "./VK Service Posting frontend"
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - "./VK Service Posting frontend:/app"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: "./VK Service Posting/.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
