"""category table add clip_list_id

Revision ID: df8d24e7bb86
Revises: f88ac6873cda
Create Date: 2025-05-25 13:16:50.647255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df8d24e7bb86"
down_revision: Union[str, None] = "f88ac6873cda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories", sa.Column("clip_list_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(None, "categories", "clip_list", ["clip_list_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "clip_list_id")
    # ### end Alembic commands ###
