"""table vk clip delete group id

Revision ID: e6e0c84413b5
Revises: 21fd24498adb
Create Date: 2025-05-25 06:27:10.749224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6e0c84413b5"
down_revision: Union[str, None] = "21fd24498adb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("vk_clip_group_id_fkey", "vk_clip", type_="foreignkey")
    op.drop_column("vk_clip", "group_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_clip",
        sa.Column("group_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "vk_clip_group_id_fkey", "vk_clip", "vk_group", ["group_id"], ["id"]
    )
    # ### end Alembic commands ###
