"""vk account add vk account url

Revision ID: 781503f4d905
Revises: 107e21c75bd4
Create Date: 2025-05-22 21:56:26.715513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "781503f4d905"
down_revision: Union[str, None] = "107e21c75bd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vk_account", sa.Column("vk_account_url", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vk_account", "vk_account_url")
    # ### end Alembic commands ###
