"""celery task add vk_group_url

Revision ID: 04b2c881d294
Revises: fa1f68046f37
Create Date: 2025-05-25 14:30:25.401845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04b2c881d294"
down_revision: Union[str, None] = "fa1f68046f37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "celery_tasks", sa.Column("vk_group_url", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("celery_tasks", "vk_group_url")
    # ### end Alembic commands ###
