"""update vk group vk clip

Revision ID: 500a9f172391
Revises: 84ab119f27db
Create Date: 2025-05-25 16:26:16.069205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "500a9f172391"
down_revision: Union[str, None] = "84ab119f27db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vk_clip", sa.Column("vk_group_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, "vk_clip", "vk_group", ["vk_group_id"], ["id"])
    op.alter_column(
        "vk_group", "vk_admin_main_id", existing_type=sa.BIGINT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vk_group", "vk_admin_main_id", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_constraint(None, "vk_clip", type_="foreignkey")
    op.drop_column("vk_clip", "vk_group_id")
    # ### end Alembic commands ###
