"""vk account add type 2

Revision ID: 107e21c75bd4
Revises: 54cd6a0505b3
Create Date: 2025-05-22 21:51:53.096421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "107e21c75bd4"
down_revision: Union[str, None] = "54cd6a0505b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vk_account", sa.Column("account_type", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vk_account", "account_type")
    # ### end Alembic commands ###
