"""schedule posting update

Revision ID: 4cbf2ebeae7b
Revises: f8b7afd8505f
Create Date: 2025-06-01 16:44:37.311545

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4cbf2ebeae7b"
down_revision: Union[str, None] = "f8b7afd8505f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule_posting", sa.Column("task_id", sa.String(), nullable=False))
    op.add_column("schedule_posting", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_posting", "status")
    op.drop_column("schedule_posting", "task_id")
    # ### end Alembic commands ###
