"""celery task table add clip list id

Revision ID: fa1f68046f37
Revises: df8d24e7bb86
Create Date: 2025-05-25 13:51:11.701546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa1f68046f37"
down_revision: Union[str, None] = "df8d24e7bb86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "celery_tasks", sa.Column("clip_list_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(None, "celery_tasks", "clip_list", ["clip_list_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "celery_tasks", type_="foreignkey")
    op.drop_column("celery_tasks", "clip_list_id")
    # ### end Alembic commands ###
