"""vk group table add 2

Revision ID: fdedad16b4e4
Revises: de19e94404e2
Create Date: 2025-05-22 22:45:58.216218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdedad16b4e4"
down_revision: Union[str, None] = "de19e94404e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vk_group",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vk_group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("vk_admin_main_id", sa.BigInteger(), nullable=False),
        sa.Column("vk_admin_poster_id", sa.BigInteger(), nullable=True),
        sa.Column("vk_group_type", sa.String(), nullable=False),
        sa.Column("vk_group_url", sa.String(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("clips_count", sa.Integer(), nullable=False),
        sa.Column("parse_status", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vk_admin_main_id"],
            ["vk_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vk_admin_poster_id"],
            ["vk_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vk_group")
    # ### end Alembic commands ###
