"""add table schedule posting

Revision ID: f8b7afd8505f
Revises: 2ce2a96423a6
Create Date: 2025-06-01 16:35:46.600201

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8b7afd8505f"
down_revision: Union[str, None] = "2ce2a96423a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_posting",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("workpost_id", sa.BigInteger(), nullable=False),
        sa.Column("clip_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workpost_id"],
            ["vk_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_posting")
    # ### end Alembic commands ###
