"""celery task add type

Revision ID: c314dbe2461d
Revises: 94d3e9fd8900
Create Date: 2025-05-24 07:37:49.295797

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c314dbe2461d"
down_revision: Union[str, None] = "94d3e9fd8900"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "celery_tasks", sa.Column("type", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("celery_tasks", "type")
    # ### end Alembic commands ###
